plugins {
    id "com.android.application"
}

android {
    namespace "com.voiceflowkeyboard.ime"
    compileSdk 35

    defaultConfig {
        applicationId "com.voiceflowkeyboard.ime"
        minSdk 26
        targetSdk 35
        versionCode 32
        versionName "0.7.0"
    }
}

dependencies {
    implementation "com.alphacephei:vosk-android:0.3.75"
    implementation "com.bihe0832.android:lib-sherpa-onnx:8.5.4"
    implementation "org.apache.commons:commons-compress:1.27.1"
    testImplementation "junit:junit:4.13.2"
}
